name: OAS lint
on:
  workflow_dispatch:
    inputs:
      oas-file-path:
        description: "The path to the oas swagger file"
        required: true
        default: "feat/oas-lint"

jobs:
  lint-oas:
    runs-on: ubuntu-latest
    steps:
      - name: Lint OAS
        run: |
          echo "FILE_PATH=${{ github.event.inputs.oas-file-path }}" >> $GITHUB_ENV
          echo "${{ env.FILE_PATH }}"
          echo "Linting OAS API definition file"
