name: OAS lint
on:
  workflow_dispatch:
    inputs:
      oas-file-path:
        description: "The path to the oas swagger file"
        required: true
        default: "swagger.yml"

jobs:
  lint-oas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Use Node.js 18"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn global add @quobix/vacuum@0.0.55
      - run: |
          echo "FILE_PATH=${{ github.event.inputs.oas-file-path }}" >> $GITHUB_ENV
          echo "${{ env.FILE_PATH }}"
          echo "Linting OAS API definition file ${{ env.FILE_PATH }}"
          vacuum lint -d ${{ github.event.inputs.oas-file-path }}
